/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class GLNVGcontext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GLNVGcontext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GLNVGcontext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_GLNVGcontext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setShader(GLNVGshader value) {
    nanovgJNI.GLNVGcontext_shader_set(swigCPtr, this, GLNVGshader.getCPtr(value), value);
  }

  public GLNVGshader getShader() {
    long cPtr = nanovgJNI.GLNVGcontext_shader_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GLNVGshader(cPtr, false);
  }

  public void setTextures(GLNVGtexture value) {
    nanovgJNI.GLNVGcontext_textures_set(swigCPtr, this, GLNVGtexture.getCPtr(value), value);
  }

  public GLNVGtexture getTextures() {
    long cPtr = nanovgJNI.GLNVGcontext_textures_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GLNVGtexture(cPtr, false);
  }

  public void setView(SWIGTYPE_p_float value) {
    nanovgJNI.GLNVGcontext_view_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getView() {
    long cPtr = nanovgJNI.GLNVGcontext_view_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setNtextures(int value) {
    nanovgJNI.GLNVGcontext_ntextures_set(swigCPtr, this, value);
  }

  public int getNtextures() {
    return nanovgJNI.GLNVGcontext_ntextures_get(swigCPtr, this);
  }

  public void setCtextures(int value) {
    nanovgJNI.GLNVGcontext_ctextures_set(swigCPtr, this, value);
  }

  public int getCtextures() {
    return nanovgJNI.GLNVGcontext_ctextures_get(swigCPtr, this);
  }

  public void setTextureId(int value) {
    nanovgJNI.GLNVGcontext_textureId_set(swigCPtr, this, value);
  }

  public int getTextureId() {
    return nanovgJNI.GLNVGcontext_textureId_get(swigCPtr, this);
  }

  public void setVertBuf(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGcontext_vertBuf_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getVertBuf() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGcontext_vertBuf_get(swigCPtr, this), true);
  }

  public void setFragSize(int value) {
    nanovgJNI.GLNVGcontext_fragSize_set(swigCPtr, this, value);
  }

  public int getFragSize() {
    return nanovgJNI.GLNVGcontext_fragSize_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    nanovgJNI.GLNVGcontext_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return nanovgJNI.GLNVGcontext_flags_get(swigCPtr, this);
  }

  public void setCalls(GLNVGcall value) {
    nanovgJNI.GLNVGcontext_calls_set(swigCPtr, this, GLNVGcall.getCPtr(value), value);
  }

  public GLNVGcall getCalls() {
    long cPtr = nanovgJNI.GLNVGcontext_calls_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GLNVGcall(cPtr, false);
  }

  public void setCcalls(int value) {
    nanovgJNI.GLNVGcontext_ccalls_set(swigCPtr, this, value);
  }

  public int getCcalls() {
    return nanovgJNI.GLNVGcontext_ccalls_get(swigCPtr, this);
  }

  public void setNcalls(int value) {
    nanovgJNI.GLNVGcontext_ncalls_set(swigCPtr, this, value);
  }

  public int getNcalls() {
    return nanovgJNI.GLNVGcontext_ncalls_get(swigCPtr, this);
  }

  public void setPaths(GLNVGpath value) {
    nanovgJNI.GLNVGcontext_paths_set(swigCPtr, this, GLNVGpath.getCPtr(value), value);
  }

  public GLNVGpath getPaths() {
    long cPtr = nanovgJNI.GLNVGcontext_paths_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GLNVGpath(cPtr, false);
  }

  public void setCpaths(int value) {
    nanovgJNI.GLNVGcontext_cpaths_set(swigCPtr, this, value);
  }

  public int getCpaths() {
    return nanovgJNI.GLNVGcontext_cpaths_get(swigCPtr, this);
  }

  public void setNpaths(int value) {
    nanovgJNI.GLNVGcontext_npaths_set(swigCPtr, this, value);
  }

  public int getNpaths() {
    return nanovgJNI.GLNVGcontext_npaths_get(swigCPtr, this);
  }

  public void setVerts(NVGvertex value) {
    nanovgJNI.GLNVGcontext_verts_set(swigCPtr, this, NVGvertex.getCPtr(value), value);
  }

  public NVGvertex getVerts() {
    long cPtr = nanovgJNI.GLNVGcontext_verts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NVGvertex(cPtr, false);
  }

  public void setCverts(int value) {
    nanovgJNI.GLNVGcontext_cverts_set(swigCPtr, this, value);
  }

  public int getCverts() {
    return nanovgJNI.GLNVGcontext_cverts_get(swigCPtr, this);
  }

  public void setNverts(int value) {
    nanovgJNI.GLNVGcontext_nverts_set(swigCPtr, this, value);
  }

  public int getNverts() {
    return nanovgJNI.GLNVGcontext_nverts_get(swigCPtr, this);
  }

  public void setUniforms(SWIGTYPE_p_unsigned_char value) {
    nanovgJNI.GLNVGcontext_uniforms_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getUniforms() {
    long cPtr = nanovgJNI.GLNVGcontext_uniforms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCuniforms(int value) {
    nanovgJNI.GLNVGcontext_cuniforms_set(swigCPtr, this, value);
  }

  public int getCuniforms() {
    return nanovgJNI.GLNVGcontext_cuniforms_get(swigCPtr, this);
  }

  public void setNuniforms(int value) {
    nanovgJNI.GLNVGcontext_nuniforms_set(swigCPtr, this, value);
  }

  public int getNuniforms() {
    return nanovgJNI.GLNVGcontext_nuniforms_get(swigCPtr, this);
  }

  public void setBoundTexture(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGcontext_boundTexture_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getBoundTexture() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGcontext_boundTexture_get(swigCPtr, this), true);
  }

  public void setStencilMask(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGcontext_stencilMask_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getStencilMask() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGcontext_stencilMask_get(swigCPtr, this), true);
  }

  public void setStencilFunc(SWIGTYPE_p_GLenum value) {
    nanovgJNI.GLNVGcontext_stencilFunc_set(swigCPtr, this, SWIGTYPE_p_GLenum.getCPtr(value));
  }

  public SWIGTYPE_p_GLenum getStencilFunc() {
    return new SWIGTYPE_p_GLenum(nanovgJNI.GLNVGcontext_stencilFunc_get(swigCPtr, this), true);
  }

  public void setStencilFuncRef(SWIGTYPE_p_GLint value) {
    nanovgJNI.GLNVGcontext_stencilFuncRef_set(swigCPtr, this, SWIGTYPE_p_GLint.getCPtr(value));
  }

  public SWIGTYPE_p_GLint getStencilFuncRef() {
    return new SWIGTYPE_p_GLint(nanovgJNI.GLNVGcontext_stencilFuncRef_get(swigCPtr, this), true);
  }

  public void setStencilFuncMask(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGcontext_stencilFuncMask_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getStencilFuncMask() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGcontext_stencilFuncMask_get(swigCPtr, this), true);
  }

  public GLNVGcontext() {
    this(nanovgJNI.new_GLNVGcontext(), true);
  }

}
