/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class GLNVGuniformLoc {
  public final static GLNVGuniformLoc GLNVG_LOC_VIEWSIZE = new GLNVGuniformLoc("GLNVG_LOC_VIEWSIZE");
  public final static GLNVGuniformLoc GLNVG_LOC_TEX = new GLNVGuniformLoc("GLNVG_LOC_TEX");
  public final static GLNVGuniformLoc GLNVG_LOC_FRAG = new GLNVGuniformLoc("GLNVG_LOC_FRAG");
  public final static GLNVGuniformLoc GLNVG_MAX_LOCS = new GLNVGuniformLoc("GLNVG_MAX_LOCS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GLNVGuniformLoc swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GLNVGuniformLoc.class + " with value " + swigValue);
  }

  private GLNVGuniformLoc(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GLNVGuniformLoc(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GLNVGuniformLoc(String swigName, GLNVGuniformLoc swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GLNVGuniformLoc[] swigValues = { GLNVG_LOC_VIEWSIZE, GLNVG_LOC_TEX, GLNVG_LOC_FRAG, GLNVG_MAX_LOCS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

