/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class GLNVGshader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GLNVGshader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GLNVGshader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_GLNVGshader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProg(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGshader_prog_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getProg() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGshader_prog_get(swigCPtr, this), true);
  }

  public void setFrag(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGshader_frag_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getFrag() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGshader_frag_get(swigCPtr, this), true);
  }

  public void setVert(SWIGTYPE_p_GLuint value) {
    nanovgJNI.GLNVGshader_vert_set(swigCPtr, this, SWIGTYPE_p_GLuint.getCPtr(value));
  }

  public SWIGTYPE_p_GLuint getVert() {
    return new SWIGTYPE_p_GLuint(nanovgJNI.GLNVGshader_vert_get(swigCPtr, this), true);
  }

  public void setLoc(SWIGTYPE_p_GLint value) {
    nanovgJNI.GLNVGshader_loc_set(swigCPtr, this, SWIGTYPE_p_GLint.getCPtr(value));
  }

  public SWIGTYPE_p_GLint getLoc() {
    long cPtr = nanovgJNI.GLNVGshader_loc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_GLint(cPtr, false);
  }

  public GLNVGshader() {
    this(nanovgJNI.new_GLNVGshader(), true);
  }

}
