/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class GLNVGpath {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GLNVGpath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GLNVGpath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_GLNVGpath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFillOffset(int value) {
    nanovgJNI.GLNVGpath_fillOffset_set(swigCPtr, this, value);
  }

  public int getFillOffset() {
    return nanovgJNI.GLNVGpath_fillOffset_get(swigCPtr, this);
  }

  public void setFillCount(int value) {
    nanovgJNI.GLNVGpath_fillCount_set(swigCPtr, this, value);
  }

  public int getFillCount() {
    return nanovgJNI.GLNVGpath_fillCount_get(swigCPtr, this);
  }

  public void setStrokeOffset(int value) {
    nanovgJNI.GLNVGpath_strokeOffset_set(swigCPtr, this, value);
  }

  public int getStrokeOffset() {
    return nanovgJNI.GLNVGpath_strokeOffset_get(swigCPtr, this);
  }

  public void setStrokeCount(int value) {
    nanovgJNI.GLNVGpath_strokeCount_set(swigCPtr, this, value);
  }

  public int getStrokeCount() {
    return nanovgJNI.GLNVGpath_strokeCount_get(swigCPtr, this);
  }

  public GLNVGpath() {
    this(nanovgJNI.new_GLNVGpath(), true);
  }

}
