/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class GLNVGcallType {
  public final static GLNVGcallType GLNVG_NONE = new GLNVGcallType("GLNVG_NONE", nanovgJNI.GLNVG_NONE_get());
  public final static GLNVGcallType GLNVG_FILL = new GLNVGcallType("GLNVG_FILL");
  public final static GLNVGcallType GLNVG_CONVEXFILL = new GLNVGcallType("GLNVG_CONVEXFILL");
  public final static GLNVGcallType GLNVG_STROKE = new GLNVGcallType("GLNVG_STROKE");
  public final static GLNVGcallType GLNVG_TRIANGLES = new GLNVGcallType("GLNVG_TRIANGLES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GLNVGcallType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GLNVGcallType.class + " with value " + swigValue);
  }

  private GLNVGcallType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GLNVGcallType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GLNVGcallType(String swigName, GLNVGcallType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GLNVGcallType[] swigValues = { GLNVG_NONE, GLNVG_FILL, GLNVG_CONVEXFILL, GLNVG_STROKE, GLNVG_TRIANGLES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

