/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public interface nanovgConstants {
  public final static int NANOVG_GLES2 = nanovgJNI.NANOVG_GLES2_get();
  public final static int NANOVG_GL_IMPLEMENTATION = nanovgJNI.NANOVG_GL_IMPLEMENTATION_get();
  public final static int NANOVG_GL_USE_STATE_FILTER = nanovgJNI.NANOVG_GL_USE_STATE_FILTER_get();
  public final static int NANOVG_GL_UNIFORMARRAY_SIZE = nanovgJNI.NANOVG_GL_UNIFORMARRAY_SIZE_get();
  public final static double NVG_PI = nanovgJNI.NVG_PI_get();
}
