/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGalign {
  public final static NVGalign NVG_ALIGN_LEFT = new NVGalign("NVG_ALIGN_LEFT", nanovgJNI.NVG_ALIGN_LEFT_get());
  public final static NVGalign NVG_ALIGN_CENTER = new NVGalign("NVG_ALIGN_CENTER", nanovgJNI.NVG_ALIGN_CENTER_get());
  public final static NVGalign NVG_ALIGN_RIGHT = new NVGalign("NVG_ALIGN_RIGHT", nanovgJNI.NVG_ALIGN_RIGHT_get());
  public final static NVGalign NVG_ALIGN_TOP = new NVGalign("NVG_ALIGN_TOP", nanovgJNI.NVG_ALIGN_TOP_get());
  public final static NVGalign NVG_ALIGN_MIDDLE = new NVGalign("NVG_ALIGN_MIDDLE", nanovgJNI.NVG_ALIGN_MIDDLE_get());
  public final static NVGalign NVG_ALIGN_BOTTOM = new NVGalign("NVG_ALIGN_BOTTOM", nanovgJNI.NVG_ALIGN_BOTTOM_get());
  public final static NVGalign NVG_ALIGN_BASELINE = new NVGalign("NVG_ALIGN_BASELINE", nanovgJNI.NVG_ALIGN_BASELINE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGalign swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGalign.class + " with value " + swigValue);
  }

  private NVGalign(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGalign(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGalign(String swigName, NVGalign swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGalign[] swigValues = { NVG_ALIGN_LEFT, NVG_ALIGN_CENTER, NVG_ALIGN_RIGHT, NVG_ALIGN_TOP, NVG_ALIGN_MIDDLE, NVG_ALIGN_BOTTOM, NVG_ALIGN_BASELINE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

