/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGblendFactor {
  public final static NVGblendFactor NVG_ZERO = new NVGblendFactor("NVG_ZERO", nanovgJNI.NVG_ZERO_get());
  public final static NVGblendFactor NVG_ONE = new NVGblendFactor("NVG_ONE", nanovgJNI.NVG_ONE_get());
  public final static NVGblendFactor NVG_SRC_COLOR = new NVGblendFactor("NVG_SRC_COLOR", nanovgJNI.NVG_SRC_COLOR_get());
  public final static NVGblendFactor NVG_ONE_MINUS_SRC_COLOR = new NVGblendFactor("NVG_ONE_MINUS_SRC_COLOR", nanovgJNI.NVG_ONE_MINUS_SRC_COLOR_get());
  public final static NVGblendFactor NVG_DST_COLOR = new NVGblendFactor("NVG_DST_COLOR", nanovgJNI.NVG_DST_COLOR_get());
  public final static NVGblendFactor NVG_ONE_MINUS_DST_COLOR = new NVGblendFactor("NVG_ONE_MINUS_DST_COLOR", nanovgJNI.NVG_ONE_MINUS_DST_COLOR_get());
  public final static NVGblendFactor NVG_SRC_ALPHA = new NVGblendFactor("NVG_SRC_ALPHA", nanovgJNI.NVG_SRC_ALPHA_get());
  public final static NVGblendFactor NVG_ONE_MINUS_SRC_ALPHA = new NVGblendFactor("NVG_ONE_MINUS_SRC_ALPHA", nanovgJNI.NVG_ONE_MINUS_SRC_ALPHA_get());
  public final static NVGblendFactor NVG_DST_ALPHA = new NVGblendFactor("NVG_DST_ALPHA", nanovgJNI.NVG_DST_ALPHA_get());
  public final static NVGblendFactor NVG_ONE_MINUS_DST_ALPHA = new NVGblendFactor("NVG_ONE_MINUS_DST_ALPHA", nanovgJNI.NVG_ONE_MINUS_DST_ALPHA_get());
  public final static NVGblendFactor NVG_SRC_ALPHA_SATURATE = new NVGblendFactor("NVG_SRC_ALPHA_SATURATE", nanovgJNI.NVG_SRC_ALPHA_SATURATE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGblendFactor swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGblendFactor.class + " with value " + swigValue);
  }

  private NVGblendFactor(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGblendFactor(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGblendFactor(String swigName, NVGblendFactor swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGblendFactor[] swigValues = { NVG_ZERO, NVG_ONE, NVG_SRC_COLOR, NVG_ONE_MINUS_SRC_COLOR, NVG_DST_COLOR, NVG_ONE_MINUS_DST_COLOR, NVG_SRC_ALPHA, NVG_ONE_MINUS_SRC_ALPHA, NVG_DST_ALPHA, NVG_ONE_MINUS_DST_ALPHA, NVG_SRC_ALPHA_SATURATE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

