/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGcolor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGcolor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGcolor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGcolor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRgba(SWIGTYPE_p_float value) {
    nanovgJNI.NVGcolor_rgba_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getRgba() {
    long cPtr = nanovgJNI.NVGcolor_rgba_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setR(float value) {
    nanovgJNI.NVGcolor_r_set(swigCPtr, this, value);
  }

  public float getR() {
    return nanovgJNI.NVGcolor_r_get(swigCPtr, this);
  }

  public void setG(float value) {
    nanovgJNI.NVGcolor_g_set(swigCPtr, this, value);
  }

  public float getG() {
    return nanovgJNI.NVGcolor_g_get(swigCPtr, this);
  }

  public void setB(float value) {
    nanovgJNI.NVGcolor_b_set(swigCPtr, this, value);
  }

  public float getB() {
    return nanovgJNI.NVGcolor_b_get(swigCPtr, this);
  }

  public void setA(float value) {
    nanovgJNI.NVGcolor_a_set(swigCPtr, this, value);
  }

  public float getA() {
    return nanovgJNI.NVGcolor_a_get(swigCPtr, this);
  }

  public NVGcolor() {
    this(nanovgJNI.new_NVGcolor(), true);
  }

}
