/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGcreateFlags {
  public final static NVGcreateFlags NVG_ANTIALIAS = new NVGcreateFlags("NVG_ANTIALIAS", nanovgJNI.NVG_ANTIALIAS_get());
  public final static NVGcreateFlags NVG_STENCIL_STROKES = new NVGcreateFlags("NVG_STENCIL_STROKES", nanovgJNI.NVG_STENCIL_STROKES_get());
  public final static NVGcreateFlags NVG_DEBUG = new NVGcreateFlags("NVG_DEBUG", nanovgJNI.NVG_DEBUG_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGcreateFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGcreateFlags.class + " with value " + swigValue);
  }

  private NVGcreateFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGcreateFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGcreateFlags(String swigName, NVGcreateFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGcreateFlags[] swigValues = { NVG_ANTIALIAS, NVG_STENCIL_STROKES, NVG_DEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

