/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGcompositeOperationState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGcompositeOperationState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGcompositeOperationState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGcompositeOperationState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSrcRGB(int value) {
    nanovgJNI.NVGcompositeOperationState_srcRGB_set(swigCPtr, this, value);
  }

  public int getSrcRGB() {
    return nanovgJNI.NVGcompositeOperationState_srcRGB_get(swigCPtr, this);
  }

  public void setDstRGB(int value) {
    nanovgJNI.NVGcompositeOperationState_dstRGB_set(swigCPtr, this, value);
  }

  public int getDstRGB() {
    return nanovgJNI.NVGcompositeOperationState_dstRGB_get(swigCPtr, this);
  }

  public void setSrcAlpha(int value) {
    nanovgJNI.NVGcompositeOperationState_srcAlpha_set(swigCPtr, this, value);
  }

  public int getSrcAlpha() {
    return nanovgJNI.NVGcompositeOperationState_srcAlpha_get(swigCPtr, this);
  }

  public void setDstAlpha(int value) {
    nanovgJNI.NVGcompositeOperationState_dstAlpha_set(swigCPtr, this, value);
  }

  public int getDstAlpha() {
    return nanovgJNI.NVGcompositeOperationState_dstAlpha_get(swigCPtr, this);
  }

  public NVGcompositeOperationState() {
    this(nanovgJNI.new_NVGcompositeOperationState(), true);
  }

}
