/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGglyphPosition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGglyphPosition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGglyphPosition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGglyphPosition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStr(String value) {
    nanovgJNI.NVGglyphPosition_str_set(swigCPtr, this, value);
  }

  public String getStr() {
    return nanovgJNI.NVGglyphPosition_str_get(swigCPtr, this);
  }

  public void setX(float value) {
    nanovgJNI.NVGglyphPosition_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return nanovgJNI.NVGglyphPosition_x_get(swigCPtr, this);
  }

  public void setMinx(float value) {
    nanovgJNI.NVGglyphPosition_minx_set(swigCPtr, this, value);
  }

  public float getMinx() {
    return nanovgJNI.NVGglyphPosition_minx_get(swigCPtr, this);
  }

  public void setMaxx(float value) {
    nanovgJNI.NVGglyphPosition_maxx_set(swigCPtr, this, value);
  }

  public float getMaxx() {
    return nanovgJNI.NVGglyphPosition_maxx_get(swigCPtr, this);
  }

  public NVGglyphPosition() {
    this(nanovgJNI.new_NVGglyphPosition(), true);
  }

}
