/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGimageFlags {
  public final static NVGimageFlags NVG_IMAGE_GENERATE_MIPMAPS = new NVGimageFlags("NVG_IMAGE_GENERATE_MIPMAPS", nanovgJNI.NVG_IMAGE_GENERATE_MIPMAPS_get());
  public final static NVGimageFlags NVG_IMAGE_REPEATX = new NVGimageFlags("NVG_IMAGE_REPEATX", nanovgJNI.NVG_IMAGE_REPEATX_get());
  public final static NVGimageFlags NVG_IMAGE_REPEATY = new NVGimageFlags("NVG_IMAGE_REPEATY", nanovgJNI.NVG_IMAGE_REPEATY_get());
  public final static NVGimageFlags NVG_IMAGE_FLIPY = new NVGimageFlags("NVG_IMAGE_FLIPY", nanovgJNI.NVG_IMAGE_FLIPY_get());
  public final static NVGimageFlags NVG_IMAGE_PREMULTIPLIED = new NVGimageFlags("NVG_IMAGE_PREMULTIPLIED", nanovgJNI.NVG_IMAGE_PREMULTIPLIED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGimageFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGimageFlags.class + " with value " + swigValue);
  }

  private NVGimageFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGimageFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGimageFlags(String swigName, NVGimageFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGimageFlags[] swigValues = { NVG_IMAGE_GENERATE_MIPMAPS, NVG_IMAGE_REPEATX, NVG_IMAGE_REPEATY, NVG_IMAGE_FLIPY, NVG_IMAGE_PREMULTIPLIED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

