/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGimageFlagsGL {
  public final static NVGimageFlagsGL NVG_IMAGE_NODELETE = new NVGimageFlagsGL("NVG_IMAGE_NODELETE", nanovgJNI.NVG_IMAGE_NODELETE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGimageFlagsGL swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGimageFlagsGL.class + " with value " + swigValue);
  }

  private NVGimageFlagsGL(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGimageFlagsGL(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGimageFlagsGL(String swigName, NVGimageFlagsGL swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGimageFlagsGL[] swigValues = { NVG_IMAGE_NODELETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

