/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGlineCap {
  public final static NVGlineCap NVG_BUTT = new NVGlineCap("NVG_BUTT");
  public final static NVGlineCap NVG_ROUND = new NVGlineCap("NVG_ROUND");
  public final static NVGlineCap NVG_SQUARE = new NVGlineCap("NVG_SQUARE");
  public final static NVGlineCap NVG_BEVEL = new NVGlineCap("NVG_BEVEL");
  public final static NVGlineCap NVG_MITER = new NVGlineCap("NVG_MITER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGlineCap swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGlineCap.class + " with value " + swigValue);
  }

  private NVGlineCap(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGlineCap(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGlineCap(String swigName, NVGlineCap swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGlineCap[] swigValues = { NVG_BUTT, NVG_ROUND, NVG_SQUARE, NVG_BEVEL, NVG_MITER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

