/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGpaint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGpaint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGpaint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGpaint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXform(SWIGTYPE_p_float value) {
    nanovgJNI.NVGpaint_xform_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getXform() {
    long cPtr = nanovgJNI.NVGpaint_xform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setExtent(SWIGTYPE_p_float value) {
    nanovgJNI.NVGpaint_extent_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getExtent() {
    long cPtr = nanovgJNI.NVGpaint_extent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setRadius(float value) {
    nanovgJNI.NVGpaint_radius_set(swigCPtr, this, value);
  }

  public float getRadius() {
    return nanovgJNI.NVGpaint_radius_get(swigCPtr, this);
  }

  public void setFeather(float value) {
    nanovgJNI.NVGpaint_feather_set(swigCPtr, this, value);
  }

  public float getFeather() {
    return nanovgJNI.NVGpaint_feather_get(swigCPtr, this);
  }

  public void setInnerColor(NVGcolor value) {
    nanovgJNI.NVGpaint_innerColor_set(swigCPtr, this, NVGcolor.getCPtr(value), value);
  }

  public NVGcolor getInnerColor() {
    long cPtr = nanovgJNI.NVGpaint_innerColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NVGcolor(cPtr, false);
  }

  public void setOuterColor(NVGcolor value) {
    nanovgJNI.NVGpaint_outerColor_set(swigCPtr, this, NVGcolor.getCPtr(value), value);
  }

  public NVGcolor getOuterColor() {
    long cPtr = nanovgJNI.NVGpaint_outerColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NVGcolor(cPtr, false);
  }

  public void setImage(int value) {
    nanovgJNI.NVGpaint_image_set(swigCPtr, this, value);
  }

  public int getImage() {
    return nanovgJNI.NVGpaint_image_get(swigCPtr, this);
  }

  public NVGpaint() {
    this(nanovgJNI.new_NVGpaint(), true);
  }

}
