/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGsolidity {
  public final static NVGsolidity NVG_SOLID = new NVGsolidity("NVG_SOLID", nanovgJNI.NVG_SOLID_get());
  public final static NVGsolidity NVG_HOLE = new NVGsolidity("NVG_HOLE", nanovgJNI.NVG_HOLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGsolidity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGsolidity.class + " with value " + swigValue);
  }

  private NVGsolidity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGsolidity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGsolidity(String swigName, NVGsolidity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGsolidity[] swigValues = { NVG_SOLID, NVG_HOLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

