/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGscissor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGscissor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGscissor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGscissor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXform(SWIGTYPE_p_float value) {
    nanovgJNI.NVGscissor_xform_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getXform() {
    long cPtr = nanovgJNI.NVGscissor_xform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setExtent(SWIGTYPE_p_float value) {
    nanovgJNI.NVGscissor_extent_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getExtent() {
    long cPtr = nanovgJNI.NVGscissor_extent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public NVGscissor() {
    this(nanovgJNI.new_NVGscissor(), true);
  }

}
