/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGtextRow {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGtextRow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGtextRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGtextRow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(String value) {
    nanovgJNI.NVGtextRow_start_set(swigCPtr, this, value);
  }

  public String getStart() {
    return nanovgJNI.NVGtextRow_start_get(swigCPtr, this);
  }

  public void setEnd(String value) {
    nanovgJNI.NVGtextRow_end_set(swigCPtr, this, value);
  }

  public String getEnd() {
    return nanovgJNI.NVGtextRow_end_get(swigCPtr, this);
  }

  public void setNext(String value) {
    nanovgJNI.NVGtextRow_next_set(swigCPtr, this, value);
  }

  public String getNext() {
    return nanovgJNI.NVGtextRow_next_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    nanovgJNI.NVGtextRow_width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return nanovgJNI.NVGtextRow_width_get(swigCPtr, this);
  }

  public void setMinx(float value) {
    nanovgJNI.NVGtextRow_minx_set(swigCPtr, this, value);
  }

  public float getMinx() {
    return nanovgJNI.NVGtextRow_minx_get(swigCPtr, this);
  }

  public void setMaxx(float value) {
    nanovgJNI.NVGtextRow_maxx_set(swigCPtr, this, value);
  }

  public float getMaxx() {
    return nanovgJNI.NVGtextRow_maxx_get(swigCPtr, this);
  }

  public NVGtextRow() {
    this(nanovgJNI.new_NVGtextRow(), true);
  }

}
