/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGtexture {
  public final static NVGtexture NVG_TEXTURE_ALPHA = new NVGtexture("NVG_TEXTURE_ALPHA", nanovgJNI.NVG_TEXTURE_ALPHA_get());
  public final static NVGtexture NVG_TEXTURE_RGBA = new NVGtexture("NVG_TEXTURE_RGBA", nanovgJNI.NVG_TEXTURE_RGBA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGtexture swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGtexture.class + " with value " + swigValue);
  }

  private NVGtexture(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGtexture(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGtexture(String swigName, NVGtexture swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGtexture[] swigValues = { NVG_TEXTURE_ALPHA, NVG_TEXTURE_RGBA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

