/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class NVGvertex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NVGvertex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NVGvertex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nanovgJNI.delete_NVGvertex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    nanovgJNI.NVGvertex_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return nanovgJNI.NVGvertex_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    nanovgJNI.NVGvertex_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return nanovgJNI.NVGvertex_y_get(swigCPtr, this);
  }

  public void setU(float value) {
    nanovgJNI.NVGvertex_u_set(swigCPtr, this, value);
  }

  public float getU() {
    return nanovgJNI.NVGvertex_u_get(swigCPtr, this);
  }

  public void setV(float value) {
    nanovgJNI.NVGvertex_v_set(swigCPtr, this, value);
  }

  public float getV() {
    return nanovgJNI.NVGvertex_v_get(swigCPtr, this);
  }

  public NVGvertex() {
    this(nanovgJNI.new_NVGvertex(), true);
  }

}
