/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public final class NVGwinding {
  public final static NVGwinding NVG_CCW = new NVGwinding("NVG_CCW", nanovgJNI.NVG_CCW_get());
  public final static NVGwinding NVG_CW = new NVGwinding("NVG_CW", nanovgJNI.NVG_CW_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NVGwinding swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NVGwinding.class + " with value " + swigValue);
  }

  private NVGwinding(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NVGwinding(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NVGwinding(String swigName, NVGwinding swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NVGwinding[] swigValues = { NVG_CCW, NVG_CW };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

