/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class SWIGTYPE_p_NVGcontext {
  private transient long swigCPtr;

  protected SWIGTYPE_p_NVGcontext(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_NVGcontext() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_NVGcontext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

