/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class SWIGTYPE_p_f_p_void_int_int_int_int_p_q_const__unsigned_char__int {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_int_int_int_int_p_q_const__unsigned_char__int(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_int_int_int_int_p_q_const__unsigned_char__int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_int_int_int_int_p_q_const__unsigned_char__int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

