/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robclouth.art_nanovg.nanovg;

public class SWIGTYPE_p_f_p_void_p_struct_NVGpaint_p_struct_NVGscissor_float_p_q_const__float_p_q_const__struct_NVGpath_int__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_p_struct_NVGpaint_p_struct_NVGscissor_float_p_q_const__float_p_q_const__struct_NVGpath_int__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_p_struct_NVGpaint_p_struct_NVGscissor_float_p_q_const__float_p_q_const__struct_NVGpath_int__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_p_struct_NVGpaint_p_struct_NVGscissor_float_p_q_const__float_p_q_const__struct_NVGpath_int__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

